apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: money-transfer-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: banking-services
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: money-transfer
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
